### ISSUE TITLE
Solving a Mysterious Heap Corruption Crash  

### ISSUE THREAD

**Issue by Awhisper** [SwiftOldDriver/iOS-Weekly#224]
https://topologyeyewear.github.io/engineering-blog/2018/03/07/heap_corruption/?utm_campaign=iOS%2BDev%2BWeekly&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B342

一个悲剧故事。。。这哥们追查诡异crash，历尽千辛万苦，最后结果是 xcode 的锅，追查crash过程中非常曲折，虽然故事很悲剧。但过程感觉值得一看

大家怎么看？

**Comment by ParsifalC** [comment]
呃，这个前几天我建 issue 了 #213，我觉得这是一次非常完整的从发现 bug 到解决 bug 再到细挖为什么的过程，值得借鉴。
Best Regards  
________________________
Parsifal Zhang (张明玮)
iOS Developer  
Mobile:158-5815-4669
Email:zmw@izmw.me
GitHub:https://github.com/ParsifalC
On 03/14/2018 16:53, Awhisper wrote: https://topologyeyewear.github.io/engineering-blog/2018/03/07/heap_corruption/?utm_campaign=iOS%2BDev%2BWeekly&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B342
一个悲剧故事。。。这哥们追查诡异crash，历尽千辛万苦，最后结果是 xcode 的锅，追查crash过程中非常曲折，虽然故事很悲剧。但过程感觉值得一看
大家怎么看？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SwiftOldDriver/iOS-Weekly","title":"SwiftOldDriver/iOS-Weekly","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SwiftOldDriver/iOS-Weekly"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Solving a Mysterious Heap Corruption Crash   (#224)"}],"action":{"name":"View Issue","url":"https://github.com/SwiftOldDriver/iOS-Weekly/issues/224"}}}

**Comment by Awhisper** [comment]
我close
