### ISSUE TITLE
如何实现 AppStore App 的自动下载

### ISSUE THREAD

**Issue by lacklock** [SwiftOldDriver/iOS-Weekly#406]
https://juejin.im/post/5b0a252d51882538b63af5c3
完全看不懂但是感觉很厉害系列

**Comment by ParsifalC** [comment]
fixed by ddbc6cc7f48353924463d0d0cb8712cff745bfe3

### [如何实现 App Store App 的自动下载](https://juejin.im/post/5b0a252d51882538b63af5c3)
如果 App Store 是开源的，要按照以下步骤实现自动下载，我想对于绝大多数开发者，都不会是难事：

1. 进入 App Store，切换 tab 到搜索界面
2. 设置搜索关键字、搜索
3. 进入列表页后，点击 App 进入详情页点击下载
4. 根据提示完成登陆、下载，并在下载完成以后跳转到推荐 Tab
5. 进入推荐 Tab 后，退出登陆

但不幸的是，App Store 并没有开源，这篇文章则通过逆向技术找到以上步骤所需要 API 并实现了自动下载，对于逆向初学者来说，这是一个很好的练手项目。
