### ISSUE TITLE
一个更好用的PNG图片压缩工具

### ISSUE THREAD

**Issue by tom510230** [SwiftOldDriver/iOS-Weekly#421]
### 推荐收录 / 意见反馈

根据提供的benchmark信息，压缩率比常见的PNG压缩工具都要高

https://github.com/chrissimpkins/Crunch/blob/master/docs/BENCHMARKS.md

#### 链接

https://github.com/chrissimpkins/Crunch

#### 理由

将PNGQUANT和ZOPFLIPNG两个工具结合起来，自动进行参数调优保证压缩率最高

**Comment by ParsifalC** [comment]
这个确实 6 啊，我测试了下同一张图，用 tinypng 和 crunch 都压缩了下，200kb 的图 tinypng 压缩后是 48kb，crunch 是 40kb，而且关键是 tinypng 的客户端是第三方的，需要申请 API key 去请求接口，免费次数有限，且是服务器处理压缩，crunch 是本地做的，完全免费。

**Comment by nuomi1** [comment]
不局限于 PNG 的话，推荐 https://github.com/JayXon/Leanify 。

---

# Features

- Support recursive minifying. (e.g. a PNG inside an APK inside a ZIP)
- Support a wide variety of file formats.
- Lightweight, one file, under 1MB, no external dependency.
- Everything is done in memory, no temporary files.
- Cross-Platform, support Windows, Linux, Mac.
- Support traverse directory recursively.
- Ability to identify file format by its data instead of name.

# File Formats

- APK file (.apk)
- Comic book archive (.cbt, .cbz)
- Microsoft Office document 2007-2013 (.docx, .xlsx, .pptx)
- Data URI (.html .htm .js .css)
- Design Web Format (.dwf, dwfx)
- EPUB file (.epub)
- FictionBook (.fb2, .fb2.zip)
- GFT file (.gft)
- gzip file (.gz, .tgz)
- Icon file (.ico)
- Java archive (.jar)
- JPEG image (.jpeg, .jpg, .jpe, .jif, .jfif, .jfi, .thm)
- Lua object file (.lua, .luac)
- OpenDocument (.odt, .ods, .odp, .odb, .odg, .odf)
- PE file (.exe, .dll, .ocx, .scr, .cpl)
- PNG image (.png, .apng)
- RDB archive (.rdb)
- Flash file (.swf)
- SVG image (.svg, .svgz)
- tar archive (.tar)
- XML document (.xml, .xsl, .xslt)
- XPInstall (.xpi)
- XPS document (.xps, .oxps)
- ZIP archive (.zip)

**Comment by ParsifalC** [comment]
@nuomi1 感谢推荐。

我试了下同一张图这几个工具的压缩效果， 原图 220kb，都是无损压缩，仅从压缩效果上来看，crunch>tinypng>leanify（这几个应该算法都是基于 Google 的 [Zopfli](https://github.com/google/zopfli)，为什么效果上差别这么大就不清楚了）。从交付成品上来说，crunch 提供有 CLI 和 GUI 工具，tinypng 有在线 web 和 GUI 工具，leanify 只有 CLI。其中 crunch 和 tinypng 的 GUI 工具批处理支持并发，而 leanify 的批处理只能逐个一次处理，实际测试中效率明显低于前两个。但 leanify 支持的压缩对象有非常多，更适合于对压缩率要求没那么高的用户。

我们也会在这期周报中简单介绍下 leanify。

## 压缩效果测试：
### tinypng
压缩后：64kb
![image](https://user-images.githubusercontent.com/7930911/40874185-c4011f04-669e-11e8-811c-8f14fe55b927.png)

### crunch
压缩后：62kb
![image](https://user-images.githubusercontent.com/7930911/40874417-8cb12078-66a1-11e8-971b-4107c591da1a.png)

### leanify
压缩后：86kb
![image](https://user-images.githubusercontent.com/7930911/40874421-9d064674-66a1-11e8-8ce3-620f6fb67c43.png)

**Comment by nuomi1** [comment]
@ParsifalC 或许和默认参数有关，建议收集一下耗时。

**Comment by ParsifalC** [comment]
可能测试样本比较小的原因吧，参数什么的就不调整做详细测试了，就是一个工具，在效果差不多的前提下，能够越简单被使用自然越会被人接受和喜欢。上面几款都有自己的特色。

**Comment by tom510230** [comment]
看了一下crunch的源码，根据PNG文件的不同特点，对压缩工具设置不同的参数值，从而确保不同的图片的压缩率最优

**Comment by ParsifalC** [comment]
### [Crunch](https://github.com/chrissimpkins/Crunch)
一款超好用的 PNG 图片无损压缩工具，提供了三种方便的使用方式：CLI、GUI 和右击服务，虽然与其他大多数压缩工具一样都是基于 Google 的 [zopfli](https://github.com/google/zopfli) 算法，但 Crunch 会根据不同的图片，动态调整压缩参数，以达到最好的压缩效果。

另外，如果对压缩率要求不高，但是希望有个万能的 CLI 压缩工具的话，[Leanify](https://github.com/JayXon/Leanify) 会是个不错的选择，它支持多达 20 多种文件格式的压缩。
